#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "› brew bundle"
  brew bundle
fi

# find the installers and run them iteratively
installers=`find . -name install.sh`
for installer in $installers ; do
  echo "Running: ${installer}";
  sh -c "${installer}";
done
